# Generated by Django 3.1.3 on 2021-05-12 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210512_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='permisson',
            new_name='permission',
        ),
    ]
